name: Node.js CI

# permissions:
#   contents: read
#   issues: read
#   checks: write
#   pull-requests: write

permissions: write-all

on: 
  pull_request: 
    branches: 
      - main
  push:
    branches: 
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - run: npm install jest-junit --save-dev && npm install jest --global
      
      - run: npm ci

      - run: npm run build --if-present

      - run: jest --coverage --reporters=default --reporters=jest-junit
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
              **/junit.xml

      - uses: artiomtr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=jpfsemp
            -Dsonar.projectKey=action-nodejs-test
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
            -Dsonar.testExecutionReportPaths=./coverage/test-report.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: covarage
            path: './coverage'

