name: Node.js CI

# permissions:
#   contents: read
#   issues: read
#   checks: write
#   pull-requests: write

permissions: write-all

on: 
  pull_request: 
    branches: 
      - main
  push:
    branches: 
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
              **/junit.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: covarage
            # Upload the coverage directory from the repository
            path: './coverage'

      - uses: artiomtr/jest-coverage-report-action@v2
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}